// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torentos.Server.Data;

#nullable disable

namespace Torentos.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220905073848_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Torentos.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 9, 5, 10, 38, 48, 176, DateTimeKind.Local).AddTicks(4747),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "What is League of Legends?League of Legends is a team-based strategy game where two teams of five powerful champions face off to destroy the other's base. Choose from over 140 champions to make epic plays, secure kills, and take down towers as you battle your way to victory.",
                            Image = "images/LeagueOfLegends.png",
                            IsDeleted = false,
                            IsPublic = false,
                            Price = 9.99m,
                            Title = "League Of Legends",
                            Type = "images/VideoGame.png"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 9, 5, 10, 38, 48, 176, DateTimeKind.Local).AddTicks(4821),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cars 2 is an animated movie that explains the life of all cars.",
                            Image = "images/Cars2.png",
                            IsDeleted = false,
                            IsPublic = false,
                            Price = 5.40m,
                            Title = "Cars 2",
                            Type = "images/Movie.png"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 9, 5, 10, 38, 48, 176, DateTimeKind.Local).AddTicks(4824),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Back in Black is the seventh studio album by Australian rock band AC/DC. It was released on 25 July 1980 by Albert Productions and Atlantic Records. It is the band's first album to feature lead singer Brian Johnson, following the death of previous lead singer Bon Scott..",
                            Image = "images/ACDC.png",
                            IsDeleted = false,
                            IsPublic = false,
                            Price = 2.30m,
                            Title = "AC-DC",
                            Type = "images/Music.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
